name: PyInstaller Build

on:
  push:
    branches: [ main ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create executable for data.py
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: https://raw.githubusercontent.com/Project0ne/gaozhuan_data/main/data.py
          options: --noconfirm,--onefile,--console
          upload_exe_with_name: data.exe
      - name: Create executable for detail.py
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: https://raw.githubusercontent.com/Project0ne/gaozhuan_data/main/detail.py
          options: --noconfirm,--onefile,--console
          upload_exe_with_name: detail.exe
